import { PilotBasin } from './types';

export const PILOT_BASINS: PilotBasin[] = [
  {
    id: 'toulouse-canal',
    name: 'Toulouse Urban Canals & Touch River',
    riverName: 'Canal du Midi & River Touch',
    country: 'France',
    flag: '🇫🇷',
    center: [43.6047, 1.4442],
    zoom: 14,
    description: 'Dense historical UNESCO canal network interconnected with the Touch River tributary. Vulnerable to storm sewer overflows and industrial heat dissipation.',
    watershedType: 'Urban Navigational Canal & Alluvial Tributary',
    historicalBaselineDate: '2024-05-12',
    recentPassDate: '2026-09-24',
    plume: {
      id: 'PLM-FR-TLS-082',
      detectedAt: '2026-09-24T10:42:18Z',
      satellite: 'Sentinel-2B (MSI)',
      orbitPass: 'R051 / Tile 31TCJ',
      lat: 43.6125,
      lng: 1.4285,
      areaSqMeters: 48500,
      flowVelocityKmH: 1.6,
      primaryPollutant: 'High-Density Microcystis (Cyanobacteria) & Organic Discharge',
      severity: 'CRITICAL',
      confidenceScore: 96.4,
      wqiEquivalent: 28,
      chlorophyllConcentrationMgM3: 78.4,
      turbidityNtu: 44.2,
    },
    downstreamPOIs: [
      {
        id: 'poi-tls-1',
        name: 'Prairie des Filtres Recreation Area & Kayak Club',
        type: 'kayak_park',
        distanceKm: 2.4,
        etaHours: 1.5,
        riskLevel: 'critical',
        healthAdvisory: 'Immediate closure of water contact recreation. Direct contact risk with neurotoxic cyanobacteria.',
        icd10Code: 'T65.8',
        diseaseDescription: 'Cyanobacterial dermatotoxin poisoning & acute ocular irritation',
      },
      {
        id: 'poi-tls-2',
        name: 'Toulouse-Empalot Municipal Drinking Intake #3',
        type: 'drinking_intake',
        distanceKm: 5.8,
        etaHours: 3.6,
        riskLevel: 'high',
        healthAdvisory: 'Precautionary diversion of raw water intake. Initiate activated carbon filtration protocol.',
        icd10Code: 'A08.4',
        diseaseDescription: 'Infectious gastroenteritis & microcystin hepatotoxicity risk',
      },
      {
        id: 'poi-tls-3',
        name: 'Pont Neuf Pedestrian Promenade',
        type: 'public_beach',
        distanceKm: 3.1,
        etaHours: 1.9,
        riskLevel: 'high',
        healthAdvisory: 'Aerosolized microcystin warning. Advise vulnerable respiratory patients to avoid bank walks.',
        icd10Code: 'J45.9',
        diseaseDescription: 'Bronchospasm & asthma exacerbation from cyanotoxin aerosols',
      },
    ],
    spectralStats: {
      ndwiMean: 0.42,
      chlorophyllMean: 78.4,
      turbidityNtu: 44.2,
      surfaceTempC: 24.8,
      anomalousPixels: 1420,
    },
  },
  {
    id: 'coimbra-mondego',
    name: 'Mondego River Catchment',
    riverName: 'Mondego River',
    country: 'Portugal',
    flag: '🇵🇹',
    center: [40.2056, -8.4196],
    zoom: 13,
    description: 'Longest river running exclusively through Portuguese territory. Subject to seasonal agricultural phosphate fertilizer runoff and warm summer eutrophication.',
    watershedType: 'Agricultural & Lowland Estuarine Basin',
    historicalBaselineDate: '2024-06-08',
    recentPassDate: '2026-09-22',
    plume: {
      id: 'PLM-PT-CBR-019',
      detectedAt: '2026-09-22T11:18:04Z',
      satellite: 'Sentinel-2A (MSI)',
      orbitPass: 'R094 / Tile 29TNE',
      lat: 40.2185,
      lng: -8.435,
      areaSqMeters: 62000,
      flowVelocityKmH: 2.1,
      primaryPollutant: 'Hyper-Eutrophic Phosphate Silt & Enterococci Plume',
      severity: 'CRITICAL',
      confidenceScore: 94.1,
      wqiEquivalent: 32,
      chlorophyllConcentrationMgM3: 64.2,
      turbidityNtu: 58.7,
    },
    downstreamPOIs: [
      {
        id: 'poi-cbr-1',
        name: 'Praia Fluvial do Choupalinho (River Beach)',
        type: 'public_beach',
        distanceKm: 3.2,
        etaHours: 1.5,
        riskLevel: 'critical',
        healthAdvisory: 'Red Flag closure. High enteric pathogen risk from upstream agricultural overflow.',
        icd10Code: 'A08.4',
        diseaseDescription: 'Acute waterborne gastroenteritis & cryptosporidiosis',
      },
      {
        id: 'poi-cbr-2',
        name: 'Mondego Lower Agricultural Irrigation Channel #4',
        type: 'drinking_intake',
        distanceKm: 7.5,
        etaHours: 3.5,
        riskLevel: 'high',
        healthAdvisory: 'Restrict irrigation on fresh produce crops to prevent crop-borne bacterial transmission.',
        icd10Code: 'A04.0',
        diseaseDescription: 'Enteropathogenic E. coli food-crop contamination',
      },
      {
        id: 'poi-cbr-3',
        name: 'Choupal National Forest Riparian Reserve',
        type: 'nature_reserve',
        distanceKm: 1.8,
        etaHours: 0.8,
        riskLevel: 'moderate',
        healthAdvisory: 'Monitor macroinvertebrate mortality and aquatic bird nesting zones.',
        icd10Code: 'Z57.8',
        diseaseDescription: 'Ecological collapse indicator & avian botulism risk',
      },
    ],
    spectralStats: {
      ndwiMean: 0.38,
      chlorophyllMean: 64.2,
      turbidityNtu: 58.7,
      surfaceTempC: 23.4,
      anomalousPixels: 1890,
    },
  },
  {
    id: 'ghent-canals',
    name: 'Ghent Port & Canal Convergence',
    riverName: 'Leie & Scheldt Urban Canals',
    country: 'Belgium',
    flag: '🇧🇪',
    center: [51.0543, 3.7174],
    zoom: 14,
    description: 'Complex junction of the Lys (Leie) and Scheldt rivers traversing medieval urban cores and heavy modern commercial shipping berths.',
    watershedType: 'Lowland Urban Industrial Canal System',
    historicalBaselineDate: '2024-04-18',
    recentPassDate: '2026-09-25',
    plume: {
      id: 'PLM-BE-GNT-104',
      detectedAt: '2026-09-25T09:55:31Z',
      satellite: 'Sentinel-2B (MSI)',
      orbitPass: 'R108 / Tile 31UET',
      lat: 51.0612,
      lng: 3.7298,
      areaSqMeters: 31000,
      flowVelocityKmH: 0.9,
      primaryPollutant: 'Chemical Turbidity & Industrial Hydrocarbon Surfactants',
      severity: 'WARNING',
      confidenceScore: 91.8,
      wqiEquivalent: 41,
      chlorophyllConcentrationMgM3: 38.6,
      turbidityNtu: 62.1,
    },
    downstreamPOIs: [
      {
        id: 'poi-gnt-1',
        name: 'Graslei Historic Waterway Promenade',
        type: 'public_beach',
        distanceKm: 1.4,
        etaHours: 1.5,
        riskLevel: 'high',
        healthAdvisory: 'Post caution signs regarding surface sheen and strong volatile organic odors.',
        icd10Code: 'T65.8',
        diseaseDescription: 'Volatile organic compound irritation & chemical dermatitis',
      },
      {
        id: 'poi-gnt-2',
        name: 'Ghent North Port Commercial Locks',
        type: 'kayak_park',
        distanceKm: 4.8,
        etaHours: 5.3,
        riskLevel: 'moderate',
        healthAdvisory: 'Deploy floating absorption booms at Sluis 2 to trap downstream hydrocarbon slick.',
        icd10Code: 'Z58.1',
        diseaseDescription: 'Occupational chemical exposure to maritime workers',
      },
    ],
    spectralStats: {
      ndwiMean: 0.49,
      chlorophyllMean: 38.6,
      turbidityNtu: 62.1,
      surfaceTempC: 19.8,
      anomalousPixels: 920,
    },
  },
  {
    id: 'benevento-calore',
    name: 'Calore Irpino & Sabato River Junction',
    riverName: 'Calore River',
    country: 'Italy',
    flag: '🇮🇹',
    center: [41.1298, 14.7818],
    zoom: 14,
    description: 'Campanian mountain-fed river junction known for rapid flash flood velocity, urban runoff, and olive oil mill seasonal discharge.',
    watershedType: 'Sub-Apennine Alluvial Basin',
    historicalBaselineDate: '2024-07-02',
    recentPassDate: '2026-09-21',
    plume: {
      id: 'PLM-IT-BNV-047',
      detectedAt: '2026-09-21T10:12:45Z',
      satellite: 'Sentinel-2A (MSI)',
      orbitPass: 'R036 / Tile 33TVF',
      lat: 41.1352,
      lng: 14.7745,
      areaSqMeters: 29500,
      flowVelocityKmH: 2.8,
      primaryPollutant: 'High Suspended Solids & Organic Oxygen-Depleting Effluent',
      severity: 'ELEVATED',
      confidenceScore: 89.2,
      wqiEquivalent: 46,
      chlorophyllConcentrationMgM3: 29.1,
      turbidityNtu: 74.5,
    },
    downstreamPOIs: [
      {
        id: 'poi-bnv-1',
        name: 'Ponte Leproso Community River Park',
        type: 'public_beach',
        distanceKm: 2.1,
        etaHours: 0.75,
        riskLevel: 'high',
        healthAdvisory: 'Fast moving turbidity plume. Advise residents to avoid riverbed wading.',
        icd10Code: 'A27.0',
        diseaseDescription: 'Leptospirosis risk from flooded urban rodent burrows',
      },
      {
        id: 'poi-bnv-2',
        name: 'Solopaca Downstream Agricultural Pump Station',
        type: 'drinking_intake',
        distanceKm: 8.2,
        etaHours: 2.9,
        riskLevel: 'moderate',
        healthAdvisory: 'Backflush sand filters to prevent pump silt jamming and micro-pathogen bypass.',
        icd10Code: 'A08.4',
        diseaseDescription: 'Turbidity-shielded microbial breakthrough in irrigation',
      },
    ],
    spectralStats: {
      ndwiMean: 0.35,
      chlorophyllMean: 29.1,
      turbidityNtu: 74.5,
      surfaceTempC: 21.2,
      anomalousPixels: 760,
    },
  },
  {
    id: 'maribor-drava',
    name: 'Drava River Urban Corridors',
    riverName: 'Drava River Tributaries',
    country: 'Slovenia',
    flag: '🇸🇮',
    center: [46.5547, 15.6459],
    zoom: 13,
    description: 'Alpine-fed major European river system flanked by urban centers and historic vineyards. High ecological value with complex damming and seasonal temperature stratification.',
    watershedType: 'Alpine-Pannonian Transitional River',
    historicalBaselineDate: '2024-08-14',
    recentPassDate: '2026-09-23',
    plume: {
      id: 'PLM-SI-MBR-003',
      detectedAt: '2026-09-23T10:05:12Z',
      satellite: 'Sentinel-2B (MSI)',
      orbitPass: 'R079 / Tile 33TVN',
      lat: 46.5592,
      lng: 15.6582,
      areaSqMeters: 22000,
      flowVelocityKmH: 3.2,
      primaryPollutant: 'Thermal Effluent & E. coli Silt Plume',
      severity: 'WARNING',
      confidenceScore: 92.5,
      wqiEquivalent: 53,
      chlorophyllConcentrationMgM3: 24.8,
      turbidityNtu: 38.4,
    },
    downstreamPOIs: [
      {
        id: 'poi-mbr-1',
        name: 'Lent Historic Riverside Promenade',
        type: 'kayak_park',
        distanceKm: 1.8,
        etaHours: 0.56,
        riskLevel: 'moderate',
        healthAdvisory: 'Elevated water temperature encouraging local bacterial incubation. Caution for water sports.',
        icd10Code: 'H60.9',
        diseaseDescription: 'Otitis externa (Swimmers ear) and superficial wound infection',
      },
      {
        id: 'poi-mbr-2',
        name: 'Drava Center Rowing & Water Sports Complex',
        type: 'public_beach',
        distanceKm: 4.2,
        etaHours: 1.3,
        riskLevel: 'high',
        healthAdvisory: 'Suspend water entry training sessions until upstream turbidity dissipates.',
        icd10Code: 'A08.4',
        diseaseDescription: 'Acute gastroenteritis from recreational water ingestion',
      },
    ],
    spectralStats: {
      ndwiMean: 0.54,
      chlorophyllMean: 24.8,
      turbidityNtu: 38.4,
      surfaceTempC: 22.9,
      anomalousPixels: 530,
    },
  },
];
